name: "Disk Space Optimizer"
author: "hugoalh"
description: "Optimize disk space for GitHub hosted runner."
inputs:
  input_listdelimiter:
    description: "{RegEx} Delimiter when the input is type of list."
    required: false
    default: ",|;|\\r?\\n"
  general:
    description: "{RegEx[]} Remove general item."
    required: false
    default: ""
  aptcache:
    description: "{Boolean} Remove Linux APT (Advanced Packaging Tools) cache."
    required: false
    default: "False"
  dockerimage:
    description: "{RegEx[]} Remove Docker image."
    required: false
    default: ""
  swap:
    description: "{Boolean} Remove Linux Swap Space."
    required: false
    default: "False"
runs:
  using: "composite"
  steps:
    - name: "Setup PowerShell Toolkit"
      uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.2.3"
    - name: "Optimize Disk Space"
      env:
        INPUT_INPUT_LISTDELIMITER: "${{inputs.input_listdelimiter}}"
        INPUT_GENERAL: "${{inputs.general}}"
        INPUT_APTCACHE: "${{inputs.aptcache}}"
        INPUT_DOCKERIMAGE: "${{inputs.dockerimage}}"
        INPUT_SWAP: "${{inputs.swap}}"
      run: |
        pwsh -NonInteractive (Join-Path -Path $Env:GITHUB_ACTION_PATH -ChildPath 'main.ps1')
      shell: "pwsh"
      continue-on-error: true
branding:
  icon: "hard-drive"
  color: "green"
